name: Text validation

on: [pull_request] # TODO: re-add push later, right now it's an obstacle

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run text
      run: |
        pip install text-validator
        validate-text text-validator.toml text/*main.txt
